#!/usr/bin/env bash
# Phase 04 / Plan 01 / Task 1 — capture LiteLLM SSE fixture corpus.
#
# Captures live SSE shapes from the contract-profile mock-LiteLLM (where
# possible) into apps/api/src/routes/agent/__fixtures__/. Tool-call shapes
# cannot be produced by LiteLLM `mock_response` (mock_response only emits a
# single content message; it cannot emit OpenAI streaming `tool_calls`
# deltas), so those fixtures are HAND-AUTHORED following the OpenAI
# streaming spec verbatim — see the source-of-truth comments at the head of
# each .sse file.
#
# Usage:
#   tools/spike/capture-sse-fixtures.sh           # capture text-only.sse only
#   FIXTURE=text-only tools/spike/capture-sse-fixtures.sh
#
# Re-running over an existing fixture overwrites it. The hand-authored
# fixtures are NOT regenerated by this script — they live under git as the
# canonical wire shapes the SSE→NDJSON parser must handle.
#
# Pre-reqs:
#   - LiteLLM contract profile up: `make contract-test-up` (or equivalent
#     `docker compose -f docker-compose.yml --profile contract up -d litellm`).
#   - LITELLM_MASTER_KEY exported to the shell.
#
# Reference: .planning/phases/04-streaming-realtime/04-RESEARCH.md §2.1.

set -euo pipefail

FIXTURE_DIR="apps/api/src/routes/agent/__fixtures__"
LITELLM_URL="${LITELLM_BASE_URL:-http://localhost:4000}"
KEY="${LITELLM_MASTER_KEY:-sk-mock-master-key}"

case "${FIXTURE:-text-only}" in
  text-only)
    out="${FIXTURE_DIR}/text-only.sse"
    {
      printf '# source: live — captured via mock-LiteLLM contract profile (qwen3.6-plus mock_response, stream:true)\n'
      printf '# Re-capture: FIXTURE=text-only tools/spike/capture-sse-fixtures.sh\n'
      curl -sN "${LITELLM_URL}/v1/chat/completions" \
        -H "Authorization: Bearer ${KEY}" \
        -H "Content-Type: application/json" \
        -d '{
          "model": "qwen3.6-plus",
          "messages": [{"role":"user","content":"hi"}],
          "stream": true,
          "stream_options": {"include_usage": true}
        }'
    } > "${out}"
    echo "Wrote ${out}"
    ;;
  *)
    echo "Hand-authored fixtures are committed under ${FIXTURE_DIR}/ — see header comments." >&2
    exit 1
    ;;
esac
