// Phase 08 / Plan 03 / Task 2 — Fastify mock-litellm server.
//
// Stands in for the real LiteLLM upstream under the `load-test-mock`
// docker-compose profile (Wave 1, plan 08-05 wires the service into
// docker-compose.yml under the `litellm` network alias).
//
// Endpoints — wire shapes mirror OpenAI / Whisper / LiteLLM enough that
// the api code path under load is indistinguishable from the real proxy:
//
//   POST /v1/audio/transcriptions  — multipart in, JSON out
//                                    { text, duration, language }.
//                                    Default latency: 1500ms ± 400ms.
//   POST /v1/chat/completions      — JSON in, JSON or SSE out
//                                    depending on `stream`.
//                                    Default latency:
//                                      sync     → 300ms ± 80ms
//                                      stream   → 200ms ± 50ms first
//                                                 token, ~30ms per
//                                                 subsequent chunk.
//   GET  /health/liveliness        — `{ status: 'ok' }`. No latency.
//
// Multipart drain (PLAN.md interfaces note): the api forwards the raw
// multipart stream via @fastify/http-proxy. If we don't iterate the
// parts, the upstream socket sits half-duplex waiting on the body
// frame — under k6 load that manifests as the api hanging until the
// client connection times out. The transcribe handler therefore drains
// `req.parts()` BEFORE simulating latency.
//
// Streaming idiom (Fastify 5): we use `reply.hijack()` then write to
// `reply.raw`. The older `reply.raw.writeHead` shortcut bypasses the
// `onSend` lifecycle and surprises CORS/auth plugins; with `hijack()`
// Fastify forfeits the response but the socket is still owned by us.

import multipart from "@fastify/multipart";
import Fastify, { type FastifyInstance } from "fastify";
import { jitter, sleep } from "./latency.js";

export interface AppConfig {
  port: number;
  host: string;
  transcribeMeanMs: number;
  transcribeSdMs: number;
  chatMeanMs: number;
  chatSdMs: number;
  streamFirstTokenMs: number;
  streamFirstTokenSdMs: number;
}

export const DEFAULT_CONFIG: AppConfig = {
  port: 4000,
  host: "0.0.0.0",
  transcribeMeanMs: 1500,
  transcribeSdMs: 400,
  chatMeanMs: 300,
  chatSdMs: 80,
  streamFirstTokenMs: 200,
  streamFirstTokenSdMs: 50,
};

interface ChatBody {
  model?: string;
  messages?: Array<{ role: string; content: string }>;
  stream?: boolean;
}

// The synthetic transcription text — same length every call so the api's
// post-processing (word-count, ledger insert) sees a stable workload.
const MOCK_TRANSCRIPT =
  "This is a mock transcription generated by the mock-litellm load-test upstream.";

// Synthetic chat completion content — short enough to keep payloads
// small under high RPS, long enough to look like a real model reply.
const MOCK_CHAT_CONTENT = "Mock response from the load-test upstream — no real model invoked.";

// Pre-tokenised SSE deltas for the streaming chat endpoint. Each chunk
// represents one logical token; the first emits after
// `streamFirstTokenMs` ± jitter, subsequent chunks every ~30ms.
const STREAM_TOKENS = MOCK_CHAT_CONTENT.split(" ").map((token, index, arr) =>
  index === arr.length - 1 ? token : `${token} `,
);
const STREAM_INTER_TOKEN_MS = 30;

function makeChatId(): string {
  return `chatcmpl-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`;
}

export function buildApp(cfg: Partial<AppConfig> = {}): FastifyInstance {
  const config: AppConfig = { ...DEFAULT_CONFIG, ...cfg };
  const app = Fastify({ logger: false });

  // Expose merged config on the instance for tests + ops introspection.
  // (Fastify lets us decorate but we don't need plugin scoping here.)
  (app as unknown as { config: AppConfig }).config = config;

  // Register multipart ONCE — re-registering inside a route throws.
  void app.register(multipart, {
    limits: {
      // 64MB: generous for whisper-large inputs (typical session <30MB).
      fileSize: 64 * 1024 * 1024,
    },
  });

  app.get("/health/liveliness", async () => ({ status: "ok" }));

  app.post("/v1/audio/transcriptions", async (req, reply) => {
    // Drain the multipart body BEFORE simulating latency, otherwise the
    // upstream connection sits in half-duplex waiting for the body
    // frame to be consumed (PLAN.md interfaces — multipart drain).
    //
    // For file parts we MUST also consume the inner stream — the
    // outer `req.parts()` iterator advances on the next call, but the
    // current part's file stream is what holds back-pressure on the
    // socket. Without `await part.toBuffer()` (or piping to /dev/null)
    // large payloads stall.
    if (req.isMultipart()) {
      for await (const part of req.parts()) {
        if (part.type === "file") {
          // Drain to EOF. We don't keep the bytes.
          await part.toBuffer();
        }
      }
    }
    await sleep(jitter(config.transcribeMeanMs, config.transcribeSdMs));
    return reply.send({
      text: MOCK_TRANSCRIPT,
      duration: 5.0,
      language: "en",
    });
  });

  app.post("/v1/chat/completions", async (req, reply) => {
    const body = (req.body ?? {}) as ChatBody;
    const wantsStream = body.stream === true;

    if (!wantsStream) {
      await sleep(jitter(config.chatMeanMs, config.chatSdMs));
      return reply.send({
        id: makeChatId(),
        object: "chat.completion",
        created: Math.floor(Date.now() / 1000),
        model: body.model ?? "gpt-4",
        choices: [
          {
            index: 0,
            message: { role: "assistant", content: MOCK_CHAT_CONTENT },
            finish_reason: "stop",
          },
        ],
        usage: {
          prompt_tokens: 10,
          completion_tokens: STREAM_TOKENS.length,
          total_tokens: 10 + STREAM_TOKENS.length,
        },
      });
    }

    // Streaming path. Fastify 5 idiom: hijack the reply, take ownership
    // of the raw socket, write SSE frames manually.
    reply.hijack();
    const raw = reply.raw;
    raw.writeHead(200, {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    });

    const id = makeChatId();
    const created = Math.floor(Date.now() / 1000);
    const model = body.model ?? "gpt-4";

    // First-token latency jitter.
    await sleep(jitter(config.streamFirstTokenMs, config.streamFirstTokenSdMs));

    for (let i = 0; i < STREAM_TOKENS.length; i++) {
      const isFirst = i === 0;
      const isLast = i === STREAM_TOKENS.length - 1;
      const chunk = {
        id,
        object: "chat.completion.chunk",
        created,
        model,
        choices: [
          {
            index: 0,
            delta: isFirst
              ? { role: "assistant", content: STREAM_TOKENS[i] }
              : { content: STREAM_TOKENS[i] },
            finish_reason: isLast ? "stop" : null,
          },
        ],
      };
      raw.write(`data: ${JSON.stringify(chunk)}\n\n`);
      if (!isLast) await sleep(STREAM_INTER_TOKEN_MS);
    }
    raw.write("data: [DONE]\n\n");
    raw.end();
  });

  return app;
}

export async function startServer(cfg: Partial<AppConfig> = {}): Promise<FastifyInstance> {
  const app = buildApp(cfg);
  const merged: AppConfig = { ...DEFAULT_CONFIG, ...cfg };
  await app.listen({ port: merged.port, host: merged.host });
  return app;
}
