// SPDX-License-Identifier: FSL-1.1-ALv2
/**
 * lint-stryker-source-assertion-excludes.test.ts — keeps stryker.config.json
 * `ignorePatterns` in sync with the deterministic detector.
 *
 * Source-assertion tests (read a MUTATED `src/**` file + assert on its text)
 * break Stryker's dry run; they are removed from the sandbox via
 * `ignorePatterns`. A hand-maintained list silently drifts (a new such test →
 * mutation-quick goes red on a missed file). So the list is GENERATED by
 * tools/stryker-source-assertion-excludes.ts (`pnpm stryker:sync-excludes`) and
 * this test fails if stryker.config.json drifts from the detector — forcing a
 * re-sync instead of a surprise CI red. fix 260530-rqk.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  ALWAYS_IGNORE,
  detectSourceAssertionTests,
  isSourceAssertionTest,
} from "./stryker-source-assertion-excludes.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");

const cfg = JSON.parse(readFileSync(join(REPO_ROOT, "stryker.config.json"), "utf8")) as {
  vitest?: { configFile?: string };
  ignorePatterns?: string[];
};

const ignored = cfg.ignorePatterns ?? [];
const ignoredTests = ignored.filter((p) => p.endsWith(".test.ts"));

describe("Stryker source-assertion ignore list", () => {
  it("uses the base vitest config (no stray Stryker-only config)", () => {
    expect(cfg.vitest?.configFile).toBe("vitest.config.ts");
  });

  it("ignores the local agent-worktree dir that pollutes the sandbox", () => {
    for (const a of ALWAYS_IGNORE) expect(ignored).toContain(a);
  });

  it("stryker.config.json ignorePatterns == detector output (run `pnpm stryker:sync-excludes` if this fails)", () => {
    const expected = [...ALWAYS_IGNORE, ...detectSourceAssertionTests(REPO_ROOT)];
    expect(ignored).toEqual(expected);
  });

  it("every ignored test file exists", () => {
    const missing = ignoredTests.filter((rel) => !existsSync(join(REPO_ROOT, rel)));
    expect(missing).toEqual([]);
  });

  it("every ignored test is genuinely a source-assertion test", () => {
    const notSourceAssertion = ignoredTests.filter(
      (rel) => !isSourceAssertionTest(readFileSync(join(REPO_ROOT, rel), "utf8")),
    );
    expect(notSourceAssertion).toEqual([]);
  });

  it("the detector finds a non-trivial set (guards a broken scan returning [])", () => {
    expect(detectSourceAssertionTests(REPO_ROOT).length).toBeGreaterThanOrEqual(10);
  });
});
